Enabled git auto-export when a course is published
mitodl/edx-platform pull request #13
Opened 2017-06-16 16:15 UTC by gsidebo

#### What are the relevant tickets?

Closes #8 

#### What's this PR do?

Allows a user to automatically export course content to Git every time they publish

#### Where should the reviewer start?

`cms/djangoapps/contentstore/signals.py`

#### How should this be manually tested?

- Set the `ENABLE_EXPORT_GIT` and `ENABLE_GIT_AUTO_EXPORT` feature flags to `True` (in `cms.env.json`)
  - If you want the export commit to have a specific name and email associated with it, set `GIT_EXPORT_DEFAULT_IDENT` in your settings to a dictionary with values for `'name'` and `'email'`, e.g.: `{'name': 'mygithubusername', 'email': 'myemail@example.com'}`
- Go into a course's advanced settings (e.g.: `http://localhost:8001/settings/advanced/course-v1:mit+gsidebo000+2017_Summer`) and set the `GIT URL` value appropriately for the test repo (e.g.: `"git@github.mit.edu:MITx-Studio2LMS/content-mit-gsidebo000-2017_Summer.git"`)
- Make a change to the course content, publish, then check the commits in your course repo

#### Any background context you want to provide?

2017-06-29 14:24 UTC, amir-qayyum-khan commented
please rebase it with mitx/ficus-1rc1

2017-06-29 17:04 UTC, gsidebo commented
@amir-qayyum-khan done

2017-06-30 11:53 UTC, amir-qayyum-khan requested changes
my question, it seem there are 3 functionalities under this PR, Should we split it, so that we can easily review.
@pdpinch any thoughts?

- GIT export 
- https://github.com/edx/edx-platform/pull/14591
- remote grade book

2017-06-30 11:53 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/signals.py
> +    # If the Git auto-export is enabled, push the course changes to Git
why we need two flags? `ENABLE_EXPORT_GIT` and `ENABLE_GIT_AUTO_EXPORT`

2017-06-30 11:53 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/signals.py
> +    if settings.FEATURES.get('ENABLE_EXPORT_GIT') and settings.FEATURES.get('ENABLE_GIT_AUTO_EXPORT'):
is `ENABLE_GIT_AUTO_EXPORT` save course periodically?

2017-06-30 11:53 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/tasks.py
> +        export_to_git(course_module.id, course_module.giturl, user=user)
can you add underscore in variable name i.e change `giturl` to `git_url `

2017-06-30 11:53 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/tasks.py
> +    Exports a course module to Git.
`Exports a course to Git.` is enough

2017-06-30 11:53 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/tasks.py
> +        LOGGER.debug('Exported course content to git: %s', course_module.id)
it should be LOGGER.info

2017-06-30 11:53 UTC, amir-qayyum-khan commented on common/lib/xmodule/xmodule/capa_base.py
> +                    msg = inst.args[0].split("\\n")[-2].split(": ", 1)[1]
why this change in PR? it seems out of scope.

2017-06-30 11:53 UTC, amir-qayyum-khan commented on common/lib/xmodule/xmodule/capa_base.py
> +                    msg = inst.args[0].split("\\n")[-2].split(": ", 1)[1]
i remember this was @pdpinch code for open edX

2017-06-30 11:53 UTC, amir-qayyum-khan commented on common/lib/xmodule/xmodule/tests/test_capa_module.py
> +                        '    exec code in g_dict\\n  File "<string>", line 67, in <module>\\n'
it seems code form @pdpinch PR https://github.com/edx/edx-platform/pull/14591/files

Not scope of this PR

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    """
this also seems to out of scope, it has nothing to do with exporting course to git?

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    course_id = SlashSeparatedCourseKey.from_deprecated_string(course_id)
why using SlashSeparatedCourseKey, why not `CourseKey.from_string(course_id)`

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    rgb = course.remote_gradebook
why not use variable name `remote_gradebook`, it look like rgb color

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    rgburl = settings.FEATURES.get('REMOTE_GRADEBOOK_URL', '')
make it `remote_gradebook_url` or `gradebook_url

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +        except Exception:  # pylint: disable=broad-except
use `data_row` or `row`

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    gtab = GradeTable()
use grade_table

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    if not rgbname:
`gradebook_name` or just `name`

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    course_id = SlashSeparatedCourseKey.from_deprecated_string(course_id)
use `CourseKey.from_string`

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    course_id = SlashSeparatedCourseKey.from_deprecated_string(course_id)
use `CourseKey.from_string`

2017-06-30 11:53 UTC, amir-qayyum-khan commented on lms/djangoapps/instructor/views/api.py
> +    assignments = [[x] for x in allgrades['assignments']]
why each assignment in array , i mean why 2d array, is `x` is it self array or single object.

2017-06-30 15:20 UTC, gsidebo commented
@amir-qayyum-khan i'm really sorry, i forgot to change the base branch for this PR. you were seeing a lot of unrelated changes and some deprecated changes in the diff. it's updated now

2017-06-30 15:20 UTC, gsidebo commented on cms/djangoapps/contentstore/signals.py
> +    if settings.FEATURES.get('ENABLE_EXPORT_GIT') and settings.FEATURES.get('ENABLE_GIT_AUTO_EXPORT'):
The purpose is to export the course contents to git every time the course is published

2017-06-30 15:20 UTC, gsidebo commented on cms/djangoapps/contentstore/signals.py
> +    # If the Git auto-export is enabled, push the course changes to Git
`ENABLE_EXPORT_GIT` allows the user to export the course contents to git by button-push, and `ENABLE_GIT_AUTO_EXPORT` automatically exports the course contents to git every time the course is published

2017-06-30 15:36 UTC, gsidebo commented on cms/djangoapps/contentstore/tasks.py
> +        LOGGER.debug('Exported course content to git: %s', course_module.id)
i'm following the convention of the rest of the tasks in this module. the other tasks use `LOGGER.debug` to log messages. examples: https://github.com/mitodl/edx-platform/pull/13/files#diff-e5cb44a7b9f87fcd4099b29724da5d24R105 and https://github.com/mitodl/edx-platform/pull/13/files#diff-e5cb44a7b9f87fcd4099b29724da5d24R118

2017-06-30 15:44 UTC, gsidebo commented on cms/djangoapps/contentstore/tasks.py
> +        export_to_git(course_module.id, course_module.giturl, user=user)
i don't think we can make that change. `giturl` is the name used by edX for this course setting (https://github.com/mitodl/edx-platform/blob/d25ede5e84334327f675e165c886c1a591ec83c2/common/lib/xmodule/xmodule/modulestore/inheritance.py#L60), and it's referenced in many different parts of the codebase.

2017-06-30 15:47 UTC, gsidebo commented on cms/djangoapps/contentstore/tasks.py
> +    Exports a course module to Git.
done

2017-06-30 15:47 UTC, gsidebo commented
@amir-qayyum-khan ready to review. sorry again for the confusion

2017-07-02 17:56 UTC, amir-qayyum-khan requested changes

2017-07-02 17:56 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/tasks.py
> +        LOGGER.debug('Exported course content to git: %s', course_module.id)
use `LOGGER.info` here

2017-07-02 17:56 UTC, amir-qayyum-khan commented on cms/djangoapps/contentstore/tasks.py
> +        export_to_git(course_module.id, course_module.giturl, user=user)
make it git_url, if this is in scope

2017-07-03 12:19 UTC, amir-qayyum-khan commented
on publishing  course i got error

``` Failed to export course content to git: GIT_REPO_EXPORT_DIR not set or path /edx/var/edxapp/export_course_repos doesn't exist, please create it, or configure a different path with GIT_REPO_EXPORT_DIR
```

2017-07-03 12:42 UTC, amir-qayyum-khan commented
functionality is working 🎉

2017-07-03 15:55 UTC, gsidebo commented on cms/djangoapps/contentstore/tasks.py
> +        export_to_git(course_module.id, course_module.giturl, user=user)
my response to this comment was hidden when i changed the base branch of this PR. here's my original response: https://github.com/mitodl/edx-platform/pull/13#discussion_r125070010

2017-07-03 15:55 UTC, gsidebo commented on cms/djangoapps/contentstore/tasks.py
> +        LOGGER.debug('Exported course content to git: %s', course_module.id)
my response to this comment was hidden when i changed the base branch of this PR. here's my original response: https://github.com/mitodl/edx-platform/pull/13#discussion_r125068258

2017-07-03 17:24 UTC, amir-qayyum-khan approved these changes
💯 👍

2017-07-03 20:02 UTC, merged