Refactored XBlockAside rendering and added support for student view
mitodl/edx-platform pull request #79
Opened 2018-02-16 22:40 UTC by gsidebo

This PR adds support for aside rendering in the LMS student view, and refactors the aside code to use the same code path in LMS/Studio for dispatching requests to the handlers defined in the aside.

2018-02-20 23:49 UTC, gsidebo commented
@noisecapella This is ready for review now. I figured out the JS errors and the repeated click handler. The barebones rapid response aside in my other PR (https://github.com/mitodl/rapid-response-xblock/pull/18) should be sufficient to test.

2018-02-21 16:13 UTC, noisecapella requested changes
Looks good overall just some minor comments. Also I think you'll need to add a test to verify the CMS view works as expected for asides

2018-02-21 16:13 UTC, noisecapella commented on common/static/common/js/xblock/core.js
> +        selector += ':not(.xblock-initialized)';
Does this fix that JS bug you found?

2018-02-21 16:13 UTC, noisecapella commented on lms/djangoapps/courseware/module_render.py
> +    wrap_xblock_aside,
I think this is an unused import

2018-02-21 16:13 UTC, noisecapella commented on openedx/core/lib/xblock_utils/__init__.py
> +        xblock_descriptor: The descriptor of the XBlock that the desired aside is decorating
Can you add a type here?

2018-02-21 16:13 UTC, noisecapella commented on openedx/core/lib/xblock_utils/__init__.py
> +        Instance of an xblock aside
Can you add a type here?

2018-02-21 16:27 UTC, gsidebo commented on common/static/common/js/xblock/core.js
> +        selector += ':not(.xblock-initialized)';
Yup. The aside renders a certain element, and that element was being selected via `.immediateDescendents(selector)` for two different elements. This selector change makes sure that any element that has already been initialized will not be selected again

2018-02-21 16:59 UTC, gsidebo commented on openedx/core/lib/xblock_utils/__init__.py
> +        xblock (xblock.core.XBlock): The XBlock that the desired aside is decorating
Made enough sense to expect an `XBlock` type here. That class inherits from `RuntimeServicesMixin`, and 
this function's only client right now is passing in an `XModuleDescriptor`, which inherits from `XBlock`

2018-02-21 17:33 UTC, noisecapella approved these changes

2018-02-21 18:44 UTC, merged

2018-02-26 16:25 UTC, pdpinch commented
Should this be opened upstream? We won't be releasing this aside into Residential MITx production until the Hawthorn release.

2018-02-26 18:20 UTC, gsidebo commented
@pdpinch We can put up a PR, but there are a couple concerns: (1) We still haven't seen the only known aside (`StructuredTagsAside`) in action, so it would be on them to make sure that still works. Adds a little to the testing burden; (2) This PR fixes the student view for asides, but there isn't an actual aside implementation that makes use of the student view (until ours is live, of course). It's possible that they wouldn't want to take the time to review for a feature that isn't relevant to them yet. I'm happy to just open it up and see what happens though