Fixed aside handler invocation to correctly set up runtime
mitodl/edx-platform pull request #80
Opened 2018-03-02 16:15 UTC by gsidebo

This PR changes the invocation of XBlockAside AJAX handler functions. It makes sure the runtime is correctly set up for the aside in both LMS and Studio

2018-03-02 16:17 UTC, gsidebo commented
I updated my rapid response PR (https://github.com/mitodl/rapid-response-xblock/pull/18). These fixes can be tested with that branch

2018-03-02 17:19 UTC, noisecapella commented
I'm seeing this error:

    edx.devstack.lms | Traceback (most recent call last):
    edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    edx.devstack.lms |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    edx.devstack.lms |     return func(*args, **kwargs)
    edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 970, in handle_xblock_callback
    edx.devstack.lms |     return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)
    edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 1090, in _invoke_xblock_handler
    edx.devstack.lms |     request, course_id, unicode(block_usage_key), aside_usage_id=aside_usage_id, course=course
    edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 1042, in get_module_by_usage_id
    edx.devstack.lms |     course=course
    edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 389, in get_module_for_descriptor
    edx.devstack.lms |     course=course
    edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 838, in get_module_for_descriptor_internal
    edx.devstack.lms |     descriptor_to_bind.bind_for_student(
    edx.devstack.lms | AttributeError: 'RapidResponseAside' object has no attribute 'bind_for_student'
    edx.devstack.lms | [02/Mar/2018 12:18:38] "GET /courses/course-v1:ReplaceStatic+ReplaceStatic+2018_T1/xblock/aside-usage-v2:block-v1$:ReplaceStatic+ReplaceStatic+2018_T1+type@problem+block@b9dca79886ef481dbade98a50de54673::rapid_response_xblock/handler/toggle_block_open_status HTTP/1.1" 500 115538

2018-03-02 18:17 UTC, gsidebo commented
Are you using my rapid response branch to test it, and is it up to date? If
so, it's a bug. I'll take a look

On Mar 2, 2018 12:20 PM, "George Schneeloch" <notifications@github.com>
wrote:

> I'm seeing this error:
>
> edx.devstack.lms | Traceback (most recent call last):
> edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
> edx.devstack.lms |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
> edx.devstack.lms |     return func(*args, **kwargs)
> edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 970, in handle_xblock_callback
> edx.devstack.lms |     return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)
> edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 1090, in _invoke_xblock_handler
> edx.devstack.lms |     request, course_id, unicode(block_usage_key), aside_usage_id=aside_usage_id, course=course
> edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 1042, in get_module_by_usage_id
> edx.devstack.lms |     course=course
> edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 389, in get_module_for_descriptor
> edx.devstack.lms |     course=course
> edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 838, in get_module_for_descriptor_internal
> edx.devstack.lms |     descriptor_to_bind.bind_for_student(
> edx.devstack.lms | AttributeError: 'RapidResponseAside' object has no attribute 'bind_for_student'
> edx.devstack.lms | [02/Mar/2018 12:18:38] "GET /courses/course-v1:ReplaceStatic+ReplaceStatic+2018_T1/xblock/aside-usage-v2:block-v1$:ReplaceStatic+ReplaceStatic+2018_T1+type@problem+block@b9dca79886ef481dbade98a50de54673::rapid_response_xblock/handler/toggle_block_open_status HTTP/1.1" 500 115538
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitodl/edx-platform/pull/80#issuecomment-369989045>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOPY-4ZwSqahH27rJrPF99b79XAiXVRfks5taX80gaJpZM4SaIQX>
> .
>

2018-03-02 21:03 UTC, noisecapella commented
Yes and it was the latest at the time

2018-03-02 22:18 UTC, gsidebo commented
@noisecapella OK try pulling from the rapid response branch and test again

2018-03-05 15:33 UTC, noisecapella commented
I can confirm it works for me now, looking over the code...

2018-03-05 15:35 UTC, noisecapella requested changes
Just the one comment, everything else looks good

2018-03-05 15:35 UTC, noisecapella commented on cms/djangoapps/contentstore/views/component.py
> +            asides = [aside_instance] if aside_instance else []
I'm not sure if you need the if clause here, since if it was `None` the previous line would fail

2018-03-05 17:02 UTC, noisecapella approved these changes

2018-03-05 17:44 UTC, merged